# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\x03ocr\" \n\nOcrRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"%\n\x0bOcrResponse\x12\x16\n\x0e\x65xtracted_text\x18\x01 \x01(\t2?\n\nOcrService\x12\x31\n\nPerformOcr\x12\x0f.ocr.OcrRequest\x1a\x10.ocr.OcrResponse\"\x00\x42-Z+github.com/example/golang-postgres-crud/ocrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/example/golang-postgres-crud/ocr'
  _globals['_OCRREQUEST']._serialized_start=18
  _globals['_OCRREQUEST']._serialized_end=50
  _globals['_OCRRESPONSE']._serialized_start=52
  _globals['_OCRRESPONSE']._serialized_end=89
  _globals['_OCRSERVICE']._serialized_start=91
  _globals['_OCRSERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
