// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.1
// source: ocr/ocr.proto

package ocr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OcrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageData []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
}

func (x *OcrRequest) Reset() {
	*x = OcrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ocr_ocr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OcrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrRequest) ProtoMessage() {}

func (x *OcrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_ocr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrRequest.ProtoReflect.Descriptor instead.
func (*OcrRequest) Descriptor() ([]byte, []int) {
	return file_ocr_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *OcrRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type OcrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExtractedText string `protobuf:"bytes,1,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
}

func (x *OcrResponse) Reset() {
	*x = OcrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ocr_ocr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OcrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrResponse) ProtoMessage() {}

func (x *OcrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_ocr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrResponse.ProtoReflect.Descriptor instead.
func (*OcrResponse) Descriptor() ([]byte, []int) {
	return file_ocr_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *OcrResponse) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

var File_ocr_ocr_proto protoreflect.FileDescriptor

var file_ocr_ocr_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x63, 0x72, 0x2f, 0x6f, 0x63, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6f, 0x63, 0x72, 0x22, 0x2b, 0x0a, 0x0a, 0x4f, 0x63, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x34, 0x0a, 0x0b, 0x4f, 0x63, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x32, 0x3f, 0x0a, 0x0a, 0x4f, 0x63, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d,
	0x4f, 0x63, 0x72, 0x12, 0x0f, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x4f, 0x63, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x4f, 0x63, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2d, 0x63,
	0x72, 0x75, 0x64, 0x2f, 0x6f, 0x63, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ocr_ocr_proto_rawDescOnce sync.Once
	file_ocr_ocr_proto_rawDescData = file_ocr_ocr_proto_rawDesc
)

func file_ocr_ocr_proto_rawDescGZIP() []byte {
	file_ocr_ocr_proto_rawDescOnce.Do(func() {
		file_ocr_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(file_ocr_ocr_proto_rawDescData)
	})
	return file_ocr_ocr_proto_rawDescData
}

var file_ocr_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ocr_ocr_proto_goTypes = []interface{}{
	(*OcrRequest)(nil),  // 0: ocr.OcrRequest
	(*OcrResponse)(nil), // 1: ocr.OcrResponse
}
var file_ocr_ocr_proto_depIdxs = []int32{
	0, // 0: ocr.OcrService.PerformOcr:input_type -> ocr.OcrRequest
	1, // 1: ocr.OcrService.PerformOcr:output_type -> ocr.OcrResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ocr_ocr_proto_init() }
func file_ocr_ocr_proto_init() {
	if File_ocr_ocr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ocr_ocr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OcrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ocr_ocr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OcrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ocr_ocr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocr_ocr_proto_goTypes,
		DependencyIndexes: file_ocr_ocr_proto_depIdxs,
		MessageInfos:      file_ocr_ocr_proto_msgTypes,
	}.Build()
	File_ocr_ocr_proto = out.File
	file_ocr_ocr_proto_rawDesc = nil
	file_ocr_ocr_proto_goTypes = nil
	file_ocr_ocr_proto_depIdxs = nil
}
